### ISSUE TITLE
Tracking issue: Make the rust book perfect

### ISSUE THREAD

**Issue by LegNeato** [LegNeato/mdbook-typst#2]
The [Rust book](https://github.com/rust-lang/book) is a good litmus test. With the latest master, the following is generated:

[book.pdf](https://github.com/LegNeato/mdbook-typst/files/13531145/book.2.pdf)

Issues:

- [x] Codeblock fence name items like `rust,ignore` are only parsed as `ignore`. This is likely a pulldown_cmark issue.
- [x] Inter-doc links are not translated.
- [ ] Filename in code examples is just sort of hanging in space.
- [x] Images are not included.
- [ ] Notes and warnings are not displayed special.
